name: Installing Python
on: [push]
jobs:
  example_matrix:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        py-version: [3.7, 3.8, 3.9]
        os: [ubuntu-latest, macos-12, windows-latest]


    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.py_version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.py_version }}

      - name: Print Python version
        run: python --version
