name: Installing Python
on: [push]
jobs:
  example_matrix:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        py-version: [3.7, 3.8, 3.9]
        os: [ubuntu-latest, macos-12, windows-latest]
   
